---
- name: "Deploiement automatise de la configuration Projet (CUB/ECOCERT)"
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Verifier que le parametre target_project a bien ete passe
      fail:
        msg: "ERREUR: Veuillez preciser le projet cible. Exemple: -e target_project=cub"
      when: target_project is not defined

    - name: Charger les donnees du projet demande
      include_vars:
        file: "../vars/project_{{ target_project }}.yml"

    - name: Extraire les VLANs et ports du projet selon le type de switch (L2 ou L3)
      set_fact:
        project_vlans: "{{ vlans_par_groupe[group_names[0]] | default([]) }}"
        project_l2_interfaces: "{{ interfaces_par_groupe[group_names[0]] | default([]) }}"
        project_l3_interfaces: "{{ l3_interfaces_par_groupe[group_names[0]] | default([]) }}"

  tasks:
    - name: 1. Synchronisation de la base VLANs (Conservation du Mgmt)
      cisco.ios.ios_vlans:
        config: "{{ mgmt_vlans + project_vlans }}"
        state: overridden

    - name: 2. Synchronisation des affectations de ports L2 (Conservation du Mgmt)
      cisco.ios.ios_l2_interfaces:
        config: "{{ mgmt_l2_interfaces + project_l2_interfaces }}"
        state: overridden

    - name: 3. Synchronisation des interfaces de routage SVI (L3)
      cisco.ios.ios_l3_interfaces:
        config: "{{ project_l3_interfaces }}"
        state: overridden
      when: project_l3_interfaces | length > 0
